'use strict';

angular.module('bronameApp')
  .controller('BroMe', function ($scope) {
    var broNames = [
      'Brohammad',
      'Broback Brobamma',
      'Broheim',
      'Broski',
      'Bromo',
      'Brotien',
      'Brodeo',
      'Brohan',
      'Brosicle',
      'Broseidon',
      'Brolonius',
      'ABroham',
      'Marco Brolo',
      'Brozo the Clown',
      'Brometheus',
      'Broseph Stalin',
      'Tony Bromo',
      'Brodo Baggins',
      'Bronas Salk',
      'Brofessor X',
      'ZamBroni',
      'Bro Chi Minh',
      'Bromer Simpson',
      'Bro J. Simpson',
      'Brocephus',
      'G.I. Bro',
      'Broseidon',
      'Tom Brody',
      'Bro Biden',
      'Tom Broksaw',
      'Nabroleon',
      'Teddy Brosevelt',
      'Bro Jangles',
      'Broskadillo',
      'Brodecahedron',
      'Tim TeBro',
      'Ted Brosby',
      'Apollo Brohno',
      'Bromar Gaddafi',
      'Brochacho',
      'Brotato',
      'Broceratops',
      'Broda',
      'Scarlett Brohansson',
      'Brobe Bryant',
      'Brobe Beef'
    ];
    
    $scope.broName = broNames[Math.floor(Math.random() * broNames.length)];
  });