'use strict';

angular.module('bronameApp')
  .controller('broname', function ($scope) {
    var broNames = [
      'Brohammad Ali',
      'Broback Brobamma',
      'Mitt Bromney',
      'Broheim',
      'Broski',
      'Bromo',
      'Brotien',
      'Brodeo',
      'Brohan',
      'Brosicle',
      'Broseidon',
      'Brolonius',
      'Abroham',
      'Marco Brolo',
      'Brozo the Clown',
      'Brometheus',
      'Broseph Stalin',
      'Tony Bromo',
      'Brodo Baggins',
      'Bronas Salk',
      'Brofessor X',
      'ZamBroni',
      'Bro Chi Minh',
      'Bromer Simpson',
      'Bro J. Simpson',
      'Brocephus',
      'G.I. Bro',
      'Broseidon',
      'Tom Brody',
      'Bro Biden',
      'Tom Broksaw',
      'Nabroleon',
      'Teddy Brosevelt',
      'Bro Jangles',
      'Broskadillo',
      'Brodecahedron',
      'Tim TeBro',
      'Ted Brosby',
      'Apollo Brohno',
      'Bromar Gaddafi',
      'Brochacho',
      'Brotato',
      'Broceratops',
      'Broda',
      'Scarlett Brohansson',
      'Brobe Bryant',
      'Brobe Beef',
      'Brovakin',
      'Brobi Wan Kenobi',
      'Brosa Parks',
      'Brozilla',
      'Broseph Goebbles',
      'Brofessional',
      'Vincent Van Brogh',
      'Edgar Allen Bro',
      'Napoleon Broneparte',
      'James Monbroe',
      'Bronald Reagan',
      'Theodore Brosevelt',
      'Brover Cleveland',
      'Bromas Jefferson',
      'Jabroni',
      'Brolaf',
      'Ringbro Starr',
      'Rainbro Dash',
      'Neville Longbrottom',
      'Lord Brodemort',
      'Bronald Weasley',
      'Bronando',
      'Bromeo',
      'Indiana Brones',
      'Han Brolo',
      'Tim Tebro'
    ];
    $scope.broName = broNames[Math.floor(Math.random() * broNames.length)];
  });